[project]
name = "mount"
version = "1.0.0"
description = "Wrapper around sys/mount.h"
authors = [{ name = "Ivan Fedorov", email = "inbox@titaniumhocker.ru" }]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.rst"
requires-python = ">=3.9,<4.0"
dependencies = []
classifiers = [
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Software Development :: Libraries"
]

[project.urls]
Repository = "https://github.com/titaniumhocker/mount"
"Bug Tracker" = "https://github.com/titaniumhocker/mount/issues"

[project.scripts]
pymnt = "mount.cli:main"

[dependency-groups]
dev = [
  "mypy>=1.1.1,<2.0.0",
  "flake8<5.0.0",
  "flake8-black>=0.3.6,<0.4.0",
  "flake8-isort>=6.0.0,<7.0.0",
  "flake8-bandit<=3.0.0",
  "flake8-bugbear<=23.3.12",
  "flake8-docstrings<1.6.0",
  "flakeheaven>=3.2.1,<4.0.0",
]

[tool.uv.build-backend]
module-root = ""
source-include = ["CHANGES.rst"]

[tool.black]
line_length = 88

[tool.isort]
profile = "black"
src_paths = ["flask_constance"]
line_length = 88

[tool.flakeheaven]
format = "colored"
max_line_length = 88
show_source = true

[tool.flakeheaven.plugins]
pyflakes = ["+*"]
pycodestyle = ["+*", "-W503", "-E501"]
flake8-docstrings = ["+*", "-D400", "-D107", "-D204", "-D105", "-D100"]
flake8-isort = ["+*"]
flake8-black = ["+*"]
flake8-bugbear = ["+*"]
flake8-bandit = ["+*"]

[tool.mypy]
files="mount"
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
check_untyped_defs = true
no_implicit_optional = true
show_error_codes = true

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
